spring.application.name=gatewayservice

server.port=8087

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

eureka.client.register-with-eureka=true

eureka.client.fetch-registry=true


# Customer Service

spring.cloud.gateway.server.webmvc.routes[0].id=customerservice
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://CUSTOMERSERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/customers/**


# Vehicle Service

spring.cloud.gateway.server.webmvc.routes[1].id=vehicleservice
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://VEHICLESERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/vehicles/**


# Driver Service

spring.cloud.gateway.server.webmvc.routes[2].id=driverservice
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://DRIVERSERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/drivers/**


# Book Service

spring.cloud.gateway.server.webmvc.routes[3].id=book-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://BOOK-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/books/**


# Payment Service

spring.cloud.gateway.server.webmvc.routes[4].id=paymentservice
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://PAYMENTSERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/payments/**


# Trip Service

spring.cloud.gateway.server.webmvc.routes[5].id=tripservice
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://TRIPSERVICE
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/trips/**


# Feedback Service

spring.cloud.gateway.server.webmvc.routes[6].id=feedbackservice
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://FEEDBACKSERVICE
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/feedback/**.